"""Update reranker training to mine 10 hard negatives per query instead of 1."""
import sys, json
sys.stdout.reconfigure(encoding='utf-8')

NOTEBOOK = 'Fine tuning codex v3.ipynb'

with open(NOTEBOOK, encoding='utf-8') as f:
    nb = json.load(f)

# ── Cell 43 (markdown): update description ──
nb['cells'][43]['source'] = [
    '### Step 4.1 \u2014 Re-mine hard negatives from the fine-tuned FAISS index\n',
    '\n',
    'The bi-encoder hard negatives mined in Phase 1 came from the **pre-trained** index. Now that we have a fine-tuned index, we re-mine harder negatives \u2014 passages the fine-tuned bi-encoder ranks highly but that come from a different source than the gold chunk.\n',
    '\n',
    'We mine **10 hard negatives per query** (up from 1). Cross-encoders score `(query, passage)` pairs independently \u2014 they don\u2019t benefit from in-batch negatives like bi-encoders do \u2014 so providing more explicit negatives gives a much stronger training signal. Each query produces 1 positive + 10 negative examples = 11 training examples.',
]

# ── Cell 44 (code): mine 10 hard negatives ──
nb['cells'][44]['source'] = [
    "# Re-mine hard negatives using the fine-tuned bi-encoder + fine-tuned FAISS index\n",
    "# Mine 10 hard negatives per query for stronger reranker training signal.\n",
    "# Use combined_train_set so reranker sees manual (Claims/Benefit) pairs too.\n",
    "reranker_train_set = combined_train_set if 'combined_train_set' in globals() else train_set\n",
    "\n",
    'print("Re-mining hard negatives from the fine-tuned FAISS index...\\n")\n',
    "\n",
    "# Batch-encode all training queries with the fine-tuned model\n",
    "train_queries = [p['query'] for p in reranker_train_set]\n",
    "ft_query_embeddings = finetuned_embed_model.encode(\n",
    "    train_queries,\n",
    "    batch_size=256,\n",
    "    normalize_embeddings=True,\n",
    "    show_progress_bar=True,\n",
    "    convert_to_numpy=True\n",
    ").astype('float32')\n",
    "\n",
    "# Search fine-tuned FAISS index \u2014 retrieve enough candidates to find 10 from different sources\n",
    "NUM_HARD_NEGATIVES = 10\n",
    "TOP_K_MINE_FT = 50  # retrieve 50 to ensure we can find 10 distinct-source negatives\n",
    "scores_ft, indices_ft = finetuned_index.search(ft_query_embeddings, TOP_K_MINE_FT)\n",
    "\n",
    "# Assign up to 10 hard negatives per training query\n",
    "neg_counts = []\n",
    'for i, pair in enumerate(tqdm(reranker_train_set, desc="Mining FT hard negatives")):\n',
    "    gold_source = pair['source_id']\n",
    "    negatives = []\n",
    "    seen_sources = {gold_source}  # skip gold source and avoid duplicates\n",
    "\n",
    "    for idx in indices_ft[i]:\n",
    "        if idx == -1:\n",
    "            continue\n",
    "        meta = chunk_metadata[idx]\n",
    "        src = str(meta['source_id'])\n",
    "        if src in seen_sources:\n",
    "            continue\n",
    "        seen_sources.add(src)\n",
    "        negatives.append(all_chunks[idx]['text'])\n",
    "        if len(negatives) == NUM_HARD_NEGATIVES:\n",
    "            break\n",
    "\n",
    "    # Fallback: if fewer than 10 found, pad with non-source-deduped candidates\n",
    "    if len(negatives) < NUM_HARD_NEGATIVES:\n",
    "        for idx in indices_ft[i]:\n",
    "            if idx == -1:\n",
    "                continue\n",
    "            meta = chunk_metadata[idx]\n",
    "            if str(meta['source_id']) == gold_source:\n",
    "                continue\n",
    "            text = all_chunks[idx]['text']\n",
    "            if text not in negatives:\n",
    "                negatives.append(text)\n",
    "            if len(negatives) == NUM_HARD_NEGATIVES:\n",
    "                break\n",
    "\n",
    "    pair['ft_negatives'] = negatives  # list of up to 10 negatives\n",
    "    pair['ft_negative'] = negatives[0] if negatives else pair['negative']  # backward compat\n",
    "    neg_counts.append(len(negatives))\n",
    "\n",
    'print(f"\\nRe-mined hard negatives for {len(reranker_train_set):,} training pairs")\n',
    'print(f"Negatives per query: min={min(neg_counts)}, max={max(neg_counts)}, avg={sum(neg_counts)/len(neg_counts):.1f}")\n',
    "\n",
    "# Also re-mine for validation set\n",
    "val_queries = [p['query'] for p in val_set]\n",
    "ft_val_embeddings = finetuned_embed_model.encode(\n",
    "    val_queries,\n",
    "    batch_size=256,\n",
    "    normalize_embeddings=True,\n",
    "    show_progress_bar=True,\n",
    "    convert_to_numpy=True\n",
    ").astype('float32')\n",
    "\n",
    "scores_val_ft, indices_val_ft = finetuned_index.search(ft_val_embeddings, TOP_K_MINE_FT)\n",
    "\n",
    'for i, pair in enumerate(tqdm(val_set, desc="Mining FT val hard negatives")):\n',
    "    gold_source = pair['source_id']\n",
    "    negatives = []\n",
    "    seen_sources = {gold_source}\n",
    "\n",
    "    for idx in indices_val_ft[i]:\n",
    "        if idx == -1:\n",
    "            continue\n",
    "        meta = chunk_metadata[idx]\n",
    "        src = str(meta['source_id'])\n",
    "        if src in seen_sources:\n",
    "            continue\n",
    "        seen_sources.add(src)\n",
    "        negatives.append(all_chunks[idx]['text'])\n",
    "        if len(negatives) == NUM_HARD_NEGATIVES:\n",
    "            break\n",
    "\n",
    "    pair['ft_negatives'] = negatives\n",
    "    pair['ft_negative'] = negatives[0] if negatives else pair['negative']\n",
    "\n",
    "# Build reranker training examples: 1 positive + 10 negatives per query\n",
    "reranker_train_examples = []\n",
    "for pair in reranker_train_set:\n",
    "    reranker_train_examples.append(\n",
    "        InputExample(texts=[pair['query'], pair['positive']], label=1.0)\n",
    "    )\n",
    "    for neg_text in pair['ft_negatives']:\n",
    "        reranker_train_examples.append(\n",
    "            InputExample(texts=[pair['query'], neg_text], label=0.0)\n",
    "        )\n",
    "\n",
    'print(f"\\nReranker training examples: {len(reranker_train_examples):,}")\n',
    'print(f"  ({len(reranker_train_set):,} queries x ~{NUM_HARD_NEGATIVES+1} examples each)")\n',
    "\n",
    "# Validation data: 1 positive + 10 negatives per query\n",
    "reranker_val_examples = []\n",
    "for pair in val_set:\n",
    "    reranker_val_examples.append(\n",
    "        InputExample(texts=[pair['query'], pair['positive']], label=1.0)\n",
    "    )\n",
    "    for neg_text in pair['ft_negatives']:\n",
    "        reranker_val_examples.append(\n",
    "            InputExample(texts=[pair['query'], neg_text], label=0.0)\n",
    "        )\n",
    "\n",
    'print(f"Reranker validation examples: {len(reranker_val_examples):,}")\n',
]
nb['cells'][44]['outputs'] = []
nb['cells'][44]['execution_count'] = None

# ── Cell 48 (code): update evaluator to use multiple negatives ──
nb['cells'][48]['source'] = [
    "# Build eval samples for CERerankingEvaluator (using fine-tuned negatives)\n",
    "reranker_eval_samples = []\n",
    "for pair in val_set:\n",
    "    reranker_eval_samples.append({\n",
    "        'query':    pair['query'],\n",
    "        'positive': [pair['positive']],\n",
    "        'negative': pair['ft_negatives']  # all 10 hard negatives\n",
    "    })\n",
    "\n",
    "reranker_evaluator = CERerankingEvaluator(\n",
    "    reranker_eval_samples,\n",
    "    name='mediquery-reranker-val'\n",
    ")\n",
    "\n",
    'print(f"Reranker evaluator: {len(reranker_eval_samples)} samples, {NUM_HARD_NEGATIVES} negatives each")\n',
]
nb['cells'][48]['outputs'] = []
nb['cells'][48]['execution_count'] = None

with open(NOTEBOOK, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f'Updated {NOTEBOOK}: cells 43, 44, 48')
print(f'Total cells: {len(nb["cells"])}')
